sudo: false

os: linux
dist: focal

language: cpp

compiler:
  - gcc
  - g++

env:
  global:
    - MAKEFLAGS="-j2"

matrix:
  include:
    - compiler: g++
      env:
        - CXX="-std=c++11"
        - CXXFLAG="-O3"
      addons:
        apt:
          update: true    
      packages:
        - liblzma-dev
        - libbz2-dev

before_script:
  - git clone --branch=master git://github.com/samtools/htslib.git
  - cd htslib; make;cd ..
  - export HTSSRC=`pwd`/htslib
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2
  - tar --bzip2 -xf boost_1_73_0.tar.bz2
  - mkdir boost; export BOOSTSRC=`pwd`/boost; cd boost_1_73_0
  - ./bootstrap.sh --with-libraries=program_options,iostreams --prefix=${BOOSTSRC}
  - ./b2 install
  - cd ..

script:
  - cd phase; make travis; cd ..
#  - make test BAMDIR=`pwd`/smallBam/
